sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    access-key-id:  LTAI5tAnxdekmCpRryKGEDTp
    access-key-secret: QxRfEvRxvSa6yeGhSqpLhQtQL4qIg5
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: leo115
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  wechat:
    appid: wx56ed56e360bd73d8
    secret: 25e7aed65b3064fdb5643f24ca29f801